// <auto-generated />
namespace n01593039MyPassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class groups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(groups));
        
        string IMigrationMetadata.Id
        {
            get { return "202402070713186_groups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
